# Generated by Django 5.2.5 on 2025-08-09 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('income_expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budget',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='income',
            options={'ordering': ['-id']},
        ),
    ]
